### ISSUE TITLE
Panic mode

### ISSUE THREAD

**Issue by dr-wolf** [kravets-levko/lua4delphi#2]
Inscript stacktrace and error handling is wanted :)

**Comment by kravets-levko** [comment]
@dr-wolf Just pushed new sources. There are properly implemented error handling, but without panic mode. So I'll leave this issue opened until implement panic mode. So subscribe for updates :smiley:

**Comment by kravets-levko** [comment]
@dr-wolf Added panic mode handling, but only for Lua states created using [TLuaCore](https://github.com/kravets-levko/lua4delphi/blob/master/lib/Lua.Core.pas#L69)
